site_name: Genetic Maze

nav:
  - Jeu:
      - Lancer le jeu: web/index.html

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false
            show_source: true
            show_root_toc_entry: false
            show_object_full_path: true
            heading_level: 2
            members_order: source
            docstring_style: google
